name: rl-infra
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip:
      - flask==2.3.3
      - numpy==1.26.0
      - pydantic==2.3.0
      - pynput==1.7.6
      - requests==2.31.0
      - scipy==1.11.2
      - torch==2.0.1
      - torchvision==0.15.2
