MODEL_ROOT_PATH = "data/online/model"
MODEL_WEIGHTS_PATH = f"{MODEL_ROOT_PATH}/weights.pt"
MODEL_ENTRY_PATH = f"{MODEL_ROOT_PATH}/entry.json"
INITIAL_EPSILON = 1
FINAL_EPSILON = 0.1
EPSILON_DECAY_RATE = 250000
