MODEL_ROOT_PATH = "data/online/model"
MODEL_WEIGHTS_PATH = f"{MODEL_ROOT_PATH}/weights.pt"
MODEL_ENTRY_PATH = f"{MODEL_ROOT_PATH}/entry.json"
INITIAL_EPSILON = 0.9
FINAL_EPSILON = 0.
EPSILON_DECAY_RATE = 1000
